package com.veikkaus.wallet.model

import jakarta.persistence.*
import java.math.BigDecimal
import java.time.Instant
import java.util.UUID

/**
 * Represents a player in the wallet system.
 *
 * This entity stores the mutable state of the player's account.
 * Access to this entity usually requires pessimistic locking to ensure consistency.
 *
 * @property id Unique identifier for the player (UUID).
 * @property name Player's display name.
 * @property balance Current wallet balance. strictly validated to never be negative via application logic and DB constraints.
 */
@Entity
@Table(name = "player")
data class Player(
    @Id
    val id: UUID,

    @Column(nullable = false)
    val name: String,

    @Column(nullable = false, precision = 20, scale = 2)
    var balance: BigDecimal
)

/**
 * Represents an immutable audit record of a wallet transaction.
 *
 * This entity serves two purposes:
 * 1. **Audit Log:** A permanent, append-only history of money movement.
 * 2. **Idempotency Guarantee:** The `transactionId` is the database
 *    primary key, enforcing uniqueness and preventing duplicate
 *    processing of the same transaction under concurrent or retry scenarios.
 *
 * Design Notes:
 * - All fields are immutable (`updatable = false`)
 * - Database primary key constraint is the final safeguard for idempotency
 *
 * @property transactionId Globally unique ID provided by the client (Game Engine).
 *           Acts as the idempotency key and primary identifier.
 * @property playerId Foreign key reference to the Player.
 * @property type The nature of the transaction (DEBIT or CREDIT).
 * @property amount The absolute value of the transaction.
 * @property balanceAfter The player's balance immediately after this transaction.
 * @property createdAt Timestamp of when the transaction was processed (UTC).
 */
@Entity
@Table(name = "wallet_transaction")
data class WalletTransaction(
    @Id
    @Column(name = "transaction_id", updatable = false)
    val transactionId: UUID,

    @Column(name = "player_id", nullable = false, updatable = false)
    val playerId: UUID,

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, updatable = false)
    val type: TransactionType,

    @Column(nullable = false, updatable = false, precision = 20, scale = 2)
    val amount: BigDecimal,

    @Column(name = "balance_after", nullable = false, updatable = false, precision = 20, scale = 2)
    val balanceAfter: BigDecimal,

    /**
     * The timestamp is generated by the Application (`Instant.now()`) rather than the Database.
     * This makes the logic testable and independent of DB timezones.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    val createdAt: Instant = Instant.now()
)

/**
 * Enum representing the direction of money movement.
 *
 * - [DEBIT]: Money leaving the wallet (Purchase).
 * - [CREDIT]: Money entering the wallet (Win/Deposit).
 */
enum class TransactionType { DEBIT, CREDIT }